### ISSUE TITLE
#Issue - MIUI Accessibility 

### ISSUE THREAD

**Issue by Rixon46** [kamaravichow/safe-dot-android#14]
i have noticed one bug after giving all the permission and after activating the app if i press the volume button volume panel is appearing but after that it's not disappearing automatically. And i can't able to alignment the dot to right side
Device: redmi note 5 pro
Rom: stock MIUI

**Comment by kamaravichow** [comment]
Yes, You're right but I'm not sure what is the reason for it.

**Comment by Rixon46** [comment]
Ok bro if you found any fix please fix it

**Comment by kamaravichow** [comment]
Looks like it's the issue with MIUI itself. It happens with all the apps with accessibility.
