### ISSUE TITLE
Can it also support clipboard access?

### ISSUE THREAD

**Issue by brookmg** [kamaravichow/safe-dot-android#15]
Clipboard is also as sensitive as Camera and microphone. Sometimes we might copy passwords from Password managers and leave it there. Phone numbers and addresses might be in there too. Maybe a purple dot for clipboard 🙂

**Comment by kamaravichow** [comment]
I'm not sure if it's possible in android.

**Comment by brookmg** [comment]
Ya, there is only `OnPrimaryClipChanged` listener I guess.
