### ISSUE TITLE
App is crashing little while after switching on the accessibility service

### ISSUE THREAD

**Issue by AamirNaseer1** [kamaravichow/safe-dot-android#17]
The app is crashing a little while after switching on the accessibility service. Here is the scenario when it is crashing if I open the app and switch on the dot service from the accessibility section and then if I switched back to the app and wait for some time then after some time app is crashing. Service is working properly and then if I restart the app and close the dots service then again its crashes.

**Comment by kamaravichow** [comment]
This bug was fixed in the latest version of the app.  i.e version - 2.2.1. 

Please upgrade to the latest version of the app to get the crash fixed.

https://play.google.com/store/apps/details?id=com.aravi.dotpro
