### ISSUE TITLE
Triggering by apps without even location permissions

### ISSUE THREAD

**Issue by maniel** [kamaravichow/safe-dot-android#20]
Basically the title, icon and notification are shown for apps like [energy ring](https://play.google.com/store/apps/details?id=you.in.spark.energy.ring.gen), [Relay](https://play.google.com/store/apps/details?id=reddit.news), that don't even use location

**Comment by kamaravichow** [comment]
The app just records the apps that are in foreground when the permission is being accessed. 

Don't depend on the logs completely.
