### ISSUE TITLE
F-Droid - hide Customisation Center

### ISSUE THREAD

**Issue by licaon-kter** [kamaravichow/safe-dot-android#23]
...if not unlockable, eg. It says "no such app" for me when I press "get pro"

Maybe detect if Play store is disabled/missing. Maybe detect if installed from F-Droid (albeit they can still have Play too though).

**Comment by kamaravichow** [comment]
For the people who cannot get it from google play... You can get it from here

https://www.buymeacoffee.com/kamaravichow/extras

**Comment by licaon-kter** [comment]
Right, maybe redirect there when you catch such an error, or in general if from F-Droid as users might want to avoid Play (or more likely :))
