### ISSUE TITLE
App localization/translation

### ISSUE THREAD

**Issue by alazizie** [kamaravichow/safe-dot-android#29]
Hello dev,
Can you please localize it to phone language or at least to let anyone to contribute 🙂.

Thanks.

**Comment by Nickoriginal** [comment]
Your language to translate on is unknown, please name it at least. Also please try the most fresh app versions, that have more translations added (if it is possible)

**Comment by Nickoriginal** [comment]
Waiting for [author](@alazizie)

**Comment by alazizie** [comment]
> Your language to translate on is unknown, please name it at least. Also please try the most fresh app versions, that have more translations added (if it is possible)

Sorry about that, it's Arabic

**Comment by Nickoriginal** [comment]
It is not available yet. You can wait for another translator or add strings for Arabic yourself.
