### ISSUE TITLE
No longer maintained app?

### ISSUE THREAD

**Issue by piyushkumar-prog** [kamaravichow/safe-dot-android#33]

**Comment by licaon-kter** [comment]
Also @kamaravichow https://github.com/safedotapp/safe-dot-android/commit/acd416bfe17ae7e3374eabf165be9e210bde441d#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9 these Firebase/MSAppcenter libs are (or they deps) not FOSS, right? You might need to make a separate gradle flavor to exclude them

**Comment by kamaravichow** [comment]
#34 I was having my exams so I'm back now
